# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d2d3d151d4f4fc1a51497d32b0c1626946ac5fb76a37be13f0b90fc524bb38ad8a9bb8264537dbf049ea3ec7c826927be7adf861826236ba1721d6423951dc3

test:
  secret_key_base: 0dffff08bd31dd9686f09f93795c38da8fe560cd61d50f5bffe62f5e7c1d4c9b5bf0b991c2cd534c072bd9f8c601b32e111fcde65b8b458fc1e05e1a56981157

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
